[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["cd backend && rm -f package-lock.json && npm install"]

[phases.build]
cmds = ["echo 'No build step required for Node.js API'"]

[start]
cmd = "cd backend && npm start"
